// This file is generated by vinext. Do not edit.
import type * as React from "react";

declare global {
  type PageProps<Route extends VinextRouteTypes.PageRoute = VinextRouteTypes.PageRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
    searchParams: Promise<Record<string, string | string[] | undefined>>;
  };

  type LayoutProps<Route extends VinextRouteTypes.LayoutRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
    children: React.ReactNode;
  } & {
    [K in VinextRouteTypes.LayoutSlotMap[Route]]: React.ReactNode;
  };

  type RouteContext<Route extends VinextRouteTypes.RouteHandlerRoute = VinextRouteTypes.RouteHandlerRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
  };
}

declare namespace VinextRouteTypes {
  type PageRoute = "/";
  type LayoutRoute = "/";
  type RouteHandlerRoute = "/api/bootstrap" | "/api/health" | "/api/lessons/[id]" | "/api/lessons/[id]/answer" | "/api/lessons/[id]/review" | "/api/lessons/[id]/revive" | "/api/monitoring" | "/api/profile" | "/api/rooms" | "/api/rooms/[code]" | "/api/shop" | "/api/streak/revive";
  type AppRoute = "/" | "/api/bootstrap" | "/api/health" | "/api/lessons/[id]" | "/api/lessons/[id]/answer" | "/api/lessons/[id]/review" | "/api/lessons/[id]/revive" | "/api/monitoring" | "/api/profile" | "/api/rooms" | "/api/rooms/[code]" | "/api/shop" | "/api/streak/revive";

  interface ParamMap {
    "/": {};
    "/api/bootstrap": {};
    "/api/health": {};
    "/api/lessons/[id]": { id: string; };
    "/api/lessons/[id]/answer": { id: string; };
    "/api/lessons/[id]/review": { id: string; };
    "/api/lessons/[id]/revive": { id: string; };
    "/api/monitoring": {};
    "/api/profile": {};
    "/api/rooms": {};
    "/api/rooms/[code]": { code: string; };
    "/api/shop": {};
    "/api/streak/revive": {};
  }

  interface LayoutSlotMap {
    "/": never;
  }
}



export {};
